baseURL = "https://nav.wiki-power.com/"
languageCode = "zh-CN"
title = "WebStack网址导航 Hugo主题"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "iplaycode"
  description = "Webstack Hugo"
