baseURL = "https://nav.wiki-power.com/"
languageCode = "zh-CN"
title = "Power's Nav"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
