name = "AutoPhugo"
license = "CCA 3.0 Unported"
licenselink = "https://github.com/kc0bfv/autophugo/blob/master/LICENSE.md"
description = "Image gallery/Photoblog Theme for Hugo."
homepage = "https://github.com/kc0bfv/autophugo/"
tags = ["gallery", "photoblog", "responsive", "mobile", "dark", "creative", "images"]
features = ["albums", "contact form", "breadcrumbs"]
min_version = "0.58.0"

authors = [
    {name = "Karl Sickendick", homepage = "https://notmet.net"},
    {name = "Pavel Kanyshev", homepage = "https://github.com/aerohub"},
]

# If porting an existing theme
[original]
  name = "Multiverse"
  homepage = "https://html5up.net/multiverse"
