name: Build GitHub Pages
on:
    push:
        branches:
            - main
            #- cur_ver_release
jobs:
    build-github-pages:
        runs-on: ubuntu-latest
        steps:
            - name: Install Hugo
              run: sudo snap install hugo
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Build Pages
              run: make
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: exampleSite/public
